spring.application.name=xp

spring.datasource.url=jdbc:postgresql://localhost:5432/xp
spring.datasource.username=postgres
spring.datasource.password=ifpb

spring.jpa.hibernate.ddl-auto=update

# data.sql: executar após o Hibernate criar/atualizar as tabelas
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true