spring.application.name=xp

spring.datasource.url=jdbc:postgresql://localhost:5432/xp
spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.password=ifpb




spring.jpa.hibernate.ddl-auto=update

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Forçar UTF-8 nas requisições e templates
spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true

# Thymeleaf
spring.thymeleaf.encoding=UTF-8

# Garantir que o servidor use UTF-8 por padrão
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML



